[build-system]
requires = [
    "setuptools",
    "wheel",
    "attr",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv]
deps =
    discover

commands =
    discover -p "*.py" -s tests
"""
